version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@nuxtjs/tailwindcss"
    versions:
    - 3.4.2
    - 3.4.3
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.12.5
    - 5.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: composer
  directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
