version: '3.4'

x-cache:
  &cache
  cache_from:
    - ${CONTAINER_REGISTRY_BASE}/php
    - ${CONTAINER_REGISTRY_BASE}/nginx

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      target: api_platform_php
      <<: *cache
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:cached

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./api
      target: api_platform_nginx
      <<: *cache
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - '8000:80'

  # Using PostgresSQL
  #db:
  #  image: postgres:10-alpine
  #  environment:
  #    - POSTGRES_DB=family_cooking
  #    - POSTGRES_PASSWORD=pswd
  #    - POSTGRES_USER=herveGuigoz
  #  volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
  #    - ./api/docker/db/data:/var/lib/postgresql/data:rw
  #  ports:
  #    - target: 5432
  #      published: 5432
  #      protocol: tcp

  # Using mySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: family_cooking
      MYSQL_USER: herveGuigoz
      MYSQL_PASSWORD: pswd
    volumes:
      - ./.docker/db/data:/var/lib/mysql:rw
    ports:
      - '3307:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8998:8080'
    depends_on:
      - db

  client:
    build:
      context: ./client
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/client
    volumes:
      - ./client:/usr/src/client:rw,cached
      - /usr/src/client/node_modules
      - ./.docker/api/var:/usr/src/client/static/data:ro
    ports:
      - '82:3000'

  h2-proxy:
    build:
      context: ./h2-proxy
    depends_on:
      - api
      - client
    ports:
      - '454:444'
      - '8453:8443'
      - '8454:8444'
